apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
  labels:
    app.kubernetes.io/version: "0.4"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: image-build
    tekton.dev/displayName: "demo-pipeline"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
      This is a demo pipeline
  params:
    - name: say-hello-image
      type: string
      default: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2"
    - name: say-world-image
      type: string
      default: "alpine"
  tasks:
    - name: say-hello
      params:
        - name: say-hello-image
          value: "$(params.say-hello-image)"
      taskSpec:
        params:
          - name: say-hello-image
        steps:
        - image: "$(params.say-hello-image)"
          script: echo 'hello there'
    - name: say-world
      params:
        - name: say-world-image
          value: "$(params.say-world-image)"
      taskSpec:
        params:
          - name: say-world-image
        steps:
        - image: "$(params.say-world-image)"
          script: echo 'world there'
    - name: say-final
      taskSpec:
        steps:
        - image: alpine
          script: echo 'world there'
