apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: image-build
    tekton.dev/displayName: "demo-pipeline"
    tekton.dev/platforms: "linux/amd64"
spec:
  params:
  - name: say-hello-image
    type: string
    default: "bash:latest"
  - name: say-world-image
    type: string
    default: "alpine"
  tasks:
  - name: say-hello
    taskSpec:
      steps:
      - image: "$(params.say-hello-image)"
        script: echo 'hello there'
  - name: say-world
    taskSpec:
      steps:
      - image: "$(params.say-world-image)"
        script: echo 'world there'